fail_fast: true

repos:

  - repo: local
    hooks:
    - id: autopep8
      name: autopep8
      entry: "autopep8"
      language: python
      language_version: python3.12
      additional_dependencies: []
      types: [python]
      args: ["--global-config=pyproject.toml"]
      require_serial: true
      verbose: true

  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: "mypy ./src/quest_metadata"
      language: python
      language_version: python3.12
      additional_dependencies: ["mypy==1.7.1",
                                "mypy-extensions==1.0.0",
                                "aiofiles==23.2.1",
                                "aiohttp==3.9.1",
                                "asyncio==3.4.3",
                                "pydantic==2.5.2",
                                "types-aiofiles==23.2.0.0",
                                "types-pillow==10.1.0.2"]
      types: [python]
      args: ["--config-file=pyproject.toml"]
      require_serial: true
      verbose: true
      pass_filenames: false

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.338
    hooks:
    - id: pyright

  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: "pylint src/quest_metadata"
      language: python
      language_version: python3.12
      additional_dependencies: []
      types: [python]
      args: ["--rcfile=pyproject.toml"]
      require_serial: true
      verbose: true
      pass_filenames: false

  - repo: local
    hooks:
    - id: isort
      name: isort
      entry: "isort"
      language: python
      language_version: python3.12
      additional_dependencies: []
      types: [python]
      args: ["--settings-path=pyproject.toml"]
      require_serial: true
      verbose: true
      pass_filenames: true

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.29.0
    hooks:
      - id: commitizen
        stages: [commit-msg]