
from typing import Any

from playwright.async_api._generated import Playwright as AsyncPlaywright

class PlaywrightContextManager:
    def __init__(self) -> None: ...
    async def __aenter__(self) -> AsyncPlaywright: ...
    async def start(self) -> AsyncPlaywright: ...
    async def __aexit__(self, *args: Any) -> None: ...
