"""mapping constants"""

GENRE_MAPPING: dict[str, str] = {
    'Action': 'Action',
    'Casual': 'Casual',
    'Adventure': 'Adventure',
    'Arcade': 'Arcade',
    'Simulation': 'Simulation',
    'Puzzle': 'Puzzle',
    'Sports': 'Sports',
    'Educational': 'Educational',
    'Social': 'Social',
    'Exploration': 'Travel & Exploration',
    'Shooter': 'Shooter',
    'Horror': 'Horror',
    'Shooting': 'Shooter',
    'Narrative': 'Narrative',
    'Fighting': 'Fighting',
    'Strategy': 'Strategy',
    'Music': 'Music & Rhythm',
    'Productivity': 'Business, Productivity & Utility',
    'Racing': 'Racing',
    'Utility': 'Business, Productivity & Utility',
    'Movie': 'Media & Streaming',
    'Art/Creativity': 'Art & Creativity',
    'Travel': 'Travel & Exploration',
    'Education': 'Educational',
    'Relaxation/Meditation': 'Health & Fitness',
    'Space/Universe': 'Space & Universe',
    'Utilities': 'Business, Productivity & Utility',
    'Travel & Exploration': 'Travel & Exploration',
    'Creativity & Design': 'Art & Creativity',
    'Documentary & History': 'Documentary & History',
    'Music & Rhythm': 'Music & Rhythm',
    'RPG (Role Playing Games)': 'RPG',
    'Health & Fitness': 'Health & Fitness',
    'Music Video': 'Media & Streaming',
    'RPG': 'RPG',
    'Media & Streaming': 'Media & Streaming',
    'Relaxation & Meditation': 'Health & Fitness',
    'Media Player': 'Media & Streaming',
    'Documentary': 'Documentary & History',
    'Nature': 'Travel & Exploration',
    'History': 'Documentary & History',
    'Movies': 'Media & Streaming',
    'Space & Universe': 'Space & Universe',
    'Dance': 'Music & Rhythm',
    'Arcade Racing': 'Racing',
    'Survival Horror': 'Horror',
    '360 Experience (non-game)': 'Non-Game Experience',
    'Business': 'Business, Productivity & Utility',
    'Casino & Poker': 'Casual',
    'Flying': 'Simulation',
    '2D': 'Casual',
    'Family': 'Casual'
}
