"""mapping constants"""

TAG_TRENDING: str = "best of "

TAG_MAPPING: dict[str, str] = {
    'Coming Soon': 'Coming Soon',
    'MR': 'Mixed Reality',
    'Top Rated CM': 'Top Rated (Current Month)',
    'Top Rated Games': 'Top Rated Games',
    'Holiday Sale 2023 [Family Shelf]': 'Family Friendly',
    'App Lab Graduates': 'App Lab Graduates',
    'Holiday Sale 2023 [Fitness Shelf]': 'Fitness',
    'Holiday Sale 2023 [Hidden Gems Shelf]': 'Hidden Gems',
    'Holiday Sale 2023 [Cozy Shelf]': 'Cozy',
    '2 Player Games': '2 Player Games',
    'Mixed Reality': 'Mixed Reality',
    'Passthrough': 'Passthrough',
    'Fitness': 'Fitness',
    'Sci-Fi (Tag)': 'Sci-Fi',
    'Screen-To-VR Adaptations': 'Screen-To-VR Adaptations',
    'Spring Promo 2024 - Family Friendly': 'Family Friendly',
    'Evergreen Nerdy Fun': 'Evergreen Nerdy Fun',
    'Goofy Gunplay': 'Goofy Gunplay',
    'Wholesome Fun': 'Wholesome Fun',
    'Cardio Workouts': 'Fitness',
    'Play With Magic': 'Play With Magic',
    'Quirky': 'Quirky',
    'Enterprise': 'Enterprise',
    'Fantasy Adventures': 'Fantasy Adventures',
    'NUX Fitness': 'Fitness',
    'Punch And Play': 'Punch And Play',
    'Award-Winning': 'Award-Winning',
    'God-Like': 'God-Like',
    'Roguelikes': 'Roguelikes',
    'Visually Appealing': 'Visually Appealing',
    'Cuteness Overload': 'Cuteness Overload',
    'Essentials': 'Essentials',
    'Narrow Escapes': 'Narrow Escapes',
    'Platformer': 'Platformer',
    'Quest Classics V2': 'Classics',
    'Apps With Celebrities': 'Apps With Celebrities',
    'Atmospheric': 'Atmospheric',
    'Experiments Gone Wrong': 'Experiments Gone Wrong',
    'Screen-To-VR Adaptations (840)': 'Screen-To-VR Adaptations',
    'Zombies': 'Zombies',
    '4+ Player Games': '4+ Player Games',
    'Building With Your Hands, Fiddling, Tinkering': 'Tinkering',
    'Hand Tracking': 'Hand Tracking',
    'Mischief Makers': 'Mischief Makers',
    'Monsters': 'Monsters',
    'Queasy-Free': 'Queasy-Free',
    'Accessible Games': 'Accessible Games',
    'Collaborative': 'Collaborative',
    'Distant Dystopias': 'Distant Dystopias',
    'Immersive': 'Immersive',
    'Insert Coin': 'Insert Coin',
    'Open World': 'Open World',
    'Tiny Worlds': 'Tiny Worlds',
    'Pop Culture': 'Pop Culture',
    'Award-Winning Experiences': 'Award-Winning',
    'Fun In The Workplace': 'Fun In The Workplace',
    'Melee Combat': 'Melee Combat',
    'Mind Over Matter': 'Mind Over Matter',
    'Tabletop Greats': 'Tabletop Greats',
    'Artistic Apps': 'Artistic',
    'Archery': 'Archery',
    'Fantasy Workouts [Top Fitness]': 'Fitness',
    'Fitness Face-Off [Top Fitness]': 'Fitness',
    'Fitness Favorites [Top Fitness]': 'Fitness',
    'Art': 'Artistic',
    'Hidden Gems: Play Alone': 'Hidden Gems',
    'Relax & Meditate': 'Relax',
    'Retro Revival': 'Retro',
    'Visual Arts': 'Visual Arts',
    'Best Active Apps BOQ23': 'Fitness',
    'City-Building': 'City-Building',
    'Cooking': 'Cooking & Food',
    'Elite Espionage': 'Elite Espionage',
    'Food': 'Cooking & Food',
    'Hidden Gems: Play Together': 'Hidden Gems',
    'Hidden Gems: Sit & Play': 'Hidden Gems',
    'Hidden Gems: Speed Demons': 'Hidden Gems',
    'Most Innovative Apps BOQ23': 'Innovative',
    'Most Innovative Games BOQ23': 'Innovative',
    'Psychological Thrillers': 'Psychological Thrillers',
    'Screen-To-VR Adaptations (887)': 'Screen-To-VR Adaptations',
    'Wacky Sports': 'Wacky',
    'Build Your Vocab': 'Build Your Vocab',
    'Minigame': 'Minigame',
    'Music Making': 'Music Making',
    'Rock Hall Of Fame': 'Rock Hall Of Fame',
    'Stretch And Move': 'Fitness',
    'Language Learning': 'Build Your Vocab',
}

GENRE_MAPPING: dict[str, str] = {
    'Action': 'Action',
    'Casual': 'Casual',
    'Adventure': 'Adventure',
    'Arcade': 'Arcade',
    'Simulation': 'Simulation',
    'Puzzle': 'Puzzle',
    'Sports': 'Sports',
    'Educational': 'Educational',
    'Social': 'Social',
    'Exploration': 'Travel & Exploration',
    'Shooter': 'Shooter',
    'Horror': 'Horror',
    'Shooting': 'Shooter',
    'Narrative': 'Narrative',
    'Fighting': 'Fighting',
    'Strategy': 'Strategy',
    'Music': 'Music & Rhythm',
    'Productivity': 'Business, Productivity & Utility',
    'Racing': 'Racing',
    'Utility': 'Business, Productivity & Utility',
    'Movie': 'Media & Streaming',
    'Art/Creativity': 'Art & Creativity',
    'Travel': 'Travel & Exploration',
    'Education': 'Educational',
    'Relaxation/Meditation': 'Health & Fitness',
    'Utilities': 'Business, Productivity & Utility',
    'Travel & Exploration': 'Travel & Exploration',
    'Creativity & Design': 'Art & Creativity',
    'Documentary & History': 'Educational',
    'Music & Rhythm': 'Music & Rhythm',
    'RPG (Role Playing Games)': 'RPG',
    'Health & Fitness': 'Health & Fitness',
    'Music Video': 'Media & Streaming',
    'RPG': 'RPG',
    'Media & Streaming': 'Media & Streaming',
    'Relaxation & Meditation': 'Health & Fitness',
    'Media Player': 'Media & Streaming',
    'Documentary': 'Educational',
    'Nature': 'Travel & Exploration',
    'History': 'Educational',
    'Movies': 'Media & Streaming',
    'Dance': 'Music & Rhythm',
    'Arcade Racing': 'Racing',
    'Survival Horror': 'Horror',
    '360 Experience (non-game)': 'Non-Game Experience',
    'Business': 'Business, Productivity & Utility',
    'Casino & Poker': 'Casual',
    'Flying': 'Simulation',
    '2D': 'Casual',
    'Family': 'Casual',
    'Rollercoaster': 'Simulation'
}

MODE_MAPPING: list[str] = [
    "Single User",
    "Multiplayer",
    "Co-op"
]
