name: Scrape Oculus app data and images

on:
  schedule:
    - cron: '0 0 * * *' # At 00:00 every day
  workflow_dispatch:

jobs:
  update:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - name: Increase swapfile size
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Set locale
        run: |
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8

      - name: Checkout previously scraped data
        uses: actions/checkout@v4
        with:
          ref: 'github/scraped-data-repo'

      - name: Checkout application files
        run: |
          git fetch --depth=1 --no-tags --prune --no-recurse-submodules origin master
          git restore --source=origin/master --worktree src
          git restore --source=origin/master --worktree .config

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install python dependencies
        run: pip install -r .config/app/requirements.txt

      - name: Execute script
        env:
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
          GOOGLE_PRIVATE_KEY_ID: ${{ secrets.GOOGLE_PRIVATE_KEY_ID }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CERT_URL: ${{ secrets.GOOGLE_CERT_URL }}
          ROOKIE_ZIP_PASSWORD: ${{ secrets.ROOKIE_ZIP_PASSWORD }}
        run: python src/quest_metadata/main.py -c .config/app/app_config.github.json
        continue-on-error: true
          
      - name: Prepare for commits
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
        continue-on-error: true

      - name: Commit Errors
        if: always()
        run: |
          git add errors
          git diff-index --quiet HEAD || git commit -m 'github_action: update errors'
        continue-on-error: true

      - name: Commit Data
        if: always()
        run: |
          git add data
          git diff-index --quiet HEAD || git commit -m 'github_action: update data'
        continue-on-error: true

      - name: Commit Resources
        if: always()
        run: |
          git add res
          git diff-index --quiet HEAD || git commit -m 'github_action: update resources'
        continue-on-error: true

      - name: Commit Last Updated
        if: always()
        run: |
          git add _last_updated.json
          git diff-index --quiet HEAD || git commit -m 'github_action: update last_updated'
        continue-on-error: true

      - name: Push commits
        if: always()
        run: |
          git push
        continue-on-error: true