name: Scrape Oculus app data and images

on:
  schedule:
    - cron: '0 0 * * *' # At 00:00 every day
  workflow_dispatch:

jobs:
  update:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
    - name: Increase swapfile
      run: |
        sudo swapoff -a
        sudo fallocate -l 15G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        sudo swapon --show

      - name: en_US.UTF-8
        run: |
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: install python packages
        run: pip install -r .config/app/requirements.txt
          
      - name: execute script
        run: python src/quest_metadata/main.py -c .config/app/github_actions.json
        continue-on-error: true
          
      - name: commit files
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git commit -am "update: github action"
          git push
