name: run src/quest_metadata.py

on:
  schedule:
    - cron: '0 0 * * *' # At 00:00 every day

jobs:
  update:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: en_US.UTF-8
        run: |
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: install python packages
        run: pip install -r .reqs/scrape.txt
          
      - name: execute script
        run: python src/quest_metadata/quest_metadata.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git commit -am "update: github action"
          git push
          
          
